language: python
python:
    - "3.7"

os: linux
dist: xenial

cache: pip

before_install:
    - export PYTHONPATH=$TRAVIS_BUILD_DIR/pyxdh:$PYTHONPATH
    - export CODECOV_TOKEN="26dd3c7d-3372-47f1-8ec4-addf2bb16706"
    - cp $TRAVIS_BUILD_DIR/script/.pyscf_conf.py ~/.pyscf_conf.py
    - pip install -r requirements.txt

matrix:
    include:
        - name: "Deprecated pyxdh"
          script:
                pytest --disable-warnings
        - name: "pyxdhalpha"
          script:
                pytest $TRAVIS_BUILD_DIR/pyxdhalpha --disable-warnings --cov=$TRAVIS_BUILD_DIR/pyxdhalpha
        - name: "Deprecated Document"
          script:
            cd $TRAVIS_BUILD_DIR/docs &&
            make html &&
            cd -

after_success:
    - coverage combine
    - codecov --token=$CODECOV_TOKEN
