language: python
os: linux
python:
    - 3.6
    - 3.7

before_install:
    - echo "
      lib_linalg_helper_safe_eigh_lindep      = 1e-50
      lib_linalg_helper_davidson_lindep       = 1e-50
      lib_linalg_helper_dsolve_lindep         = 1e-50
      lib_linalg_helper_davidson_max_memory   = 4000
      " > ~/.pyscf_conf.py
    - export PYTHONPATH=$TRAVIS_BUILD_DIR/src:$PYTHONPATH
    - pip install -r requirements.txt

script:
    - pytest
    - cd $TRAVIS_BUILD_DIR/docs &&
      make html

