language: python
os: linux
dist: xenial
python:
    - 3.6
    - 3.7

env:
    - PYTHONPATH=$TRAVIS_BUILD_DIR/src:$PYTHONPATH

before_install:
    - cp $TRAVIS_BUILD_DIR/script/.pyscf_conf.py ~/.pyscf_conf.py
    - sudo apt-get update
    - sudo apt-get install -y pandoc
    - pip install -r requirements.txt

script:
    - pytest --disable-warnings
    - cd $TRAVIS_BUILD_DIR/docs &&
      make html

