language: python
os: linux
dist: xenial
python:
    - 3.6
    - 3.7

before_install:
    - cp $TRAVIS_BUILD_DIR/script/.pyscf_conf.py ~/.pyscf_conf.py
    - export PYTHONPATH=$TRAVIS_BUILD_DIR/src:$PYTHONPATH
    - pip install -r requirements.txt

script:
    - pytest --disable-warnings
    - cd $TRAVIS_BUILD_DIR/docs &&
      make html

